### ISSUE TITLE
To add new raw for each new position

### ISSUE THREAD

**Issue by Kehalpola** [suresh-n/richdotin#37]
Need to modify code to add each new position raw in position box. currently showing only 1 posiotion in position box.
Thank you
<img width="535" alt="Untitled" src="https://github.com/suresh-n/richdotin/assets/135952412/82cb3bc5-7e4f-4789-9e09-620fdf47ef9e">

**Comment by suresh-n** [comment]
Hi @Kehalpola please try using this https://github.com/suresh-n/RichDotinScalperApp1.git i'm no more developing this tkinter repo.
